"""empty message

Revision ID: 4d1af98d3ffe
Revises: 7d94df3bbf97
Create Date: 2020-03-02 22:16:16.992025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1af98d3ffe'
down_revision = '7d94df3bbf97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flash_id', sa.String(length=64), nullable=True))
    op.drop_constraint('users_person_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['flash_id'])
    op.drop_column('users', 'person_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('person_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_person_id_key', 'users', ['person_id'])
    op.drop_column('users', 'flash_id')
    # ### end Alembic commands ###
